# Generated by Django 2.1.5 on 2020-02-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0004_auto_20200221_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name_plural': 'Allergies'},
        ),
    ]
